[package]
name = "proof-of-love"
version = "0.1.0"
description = "On-chain Groth16 verifier for Proof of Love wealth tiers"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "proof_of_love"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
groth16-solana = "0.2.0"

[lints.rust.unexpected_cfgs]
level = "allow"
check-cfg = [
    'cfg(feature, values("anchor-debug", "custom-heap", "custom-panic"))',
]