[features]
seeds = false
skip-lint = false

[programs.localnet]
proof_of_love = "BBDtJxqUFWpCXMvZjtCFQyYGJ698o84H3RpqcJQjnGLR"

[programs.devnet]
proof_of_love = "BBDtJxqUFWpCXMvZjtCFQyYGJ698o84H3RpqcJQjnGLR"

[toolchain]
anchor_version = "0.31.1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"